[Service]
ExecStart=
ExecStart=/usr/bin/suricata -q 0 -c /etc/suricata/suricata.yaml -s /etc/suricata/rules/local.rules --pidfile /run/suricata.pid --set outputs.1.eve-log.xff.enabled=yes --set outputs.1.eve-log.xff.mode=overwrite --set outputs.1.eve-log.xff.deployment=reverse --set outputs.1.eve-log.xff.header=X-Forwarded-For
